name: To-EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set image version (tag)
      id: image_version
      run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tarteelgh/expense-tracker:${{ steps.image_version.outputs.gitsha }}
    - name: Publish docker image
      run: docker push ghcr.io/tarteelgh/expense-tracker:${{ steps.image_version.outputs.gitsha }}
    - name: configure docker host
      uses: tarteelgh/
      with:
        host: ec2-13-40-213-111.eu-west-2.compute.amazonaws.com
        user: ubuntu
        ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: deploy
      run: docker compose -f docker-compose-prod.yml up -d
      env:
        GIT_VERSION: ${{ steps.image_version.outputs.gitsha }}
    - name: print logs
      if: always() # This step will be executed even if previous steps fails
      run: docker compose logs