name: EC2-Push

on:
  push:
    branches: [ "main" ]

jobs:
    deploy:
      name: EC2 Instance
      runs-on: ubuntu-latest || self-hosted
      
    steps:
    - name: Checkout Code
    - uses: actions/checkout@v3
    
    - name: Deploy-to-EC2-instance
      
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2-KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "home"
